project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Data Apothecary's Notes"

  navbar:
    left:
     # - href: index.qmd
     #   text: Home

      - href: method/index.qmd
        text: Methods

      - href: reporting/index.qmd
        text: Reporting

      - href: programming/index.qmd
        text: Programming

      - href: about.qmd
        text: About

    right: 
      - icon: github
        href: https://github.com/andreaczhang/data-apothecary-notes
        
format:
  html:
    theme: styles.scss
    # css: styles.css
    toc: true

filters: 
  - webr

