project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Data Apothecary's Notes"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: study_design/index.qmd
        text: Study design

      - href: inference/index.qmd
        text: Inference

      - href: models/index.qmd
        text: Models

      - href: reporting/index.qmd
        text: Reporting

      - href: programming/index.qmd
        text: Programming

      - href: about.qmd
        text: About

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

filters: 
  - webr

