---
title: "Google 5-Day Gen AI Intensive"
description: |
  Notes from the intensive course on GenAI
author: "Chi Zhang"
date: "2024-11-11"
categories: [GenAI]
sidebar: false
code-block-bg: true
code-block-border-left: true
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
---

This is the notes from Google's [5 day intensive course on Gen AI](https://rsvp.withgoogle.com/events/google-generative-ai-intensive). The topics for the five days are: 

* Day 1: Foundational Models & Prompt Engineering - Explore the evolution of LLMs, from transformers to techniques like fine-tuning and inference acceleration. Get trained with the art of prompt engineering for optimal LLM interaction.

* Day 2: Embeddings and Vector Stores/Databases - Learn about the conceptual underpinning of embeddings and vector databases, including embedding methods, vector search algorithms, and real-world applications with LLMs, as well as their tradeoffs.

* Day 3: Generative AI Agents - Learn to build sophisticated AI agents by understanding their core components and the iterative development process.

* Day 4: Domain-Specific LLMs - Delve into the creation and application of specialized LLMs like SecLM and Med-PaLM, with insights from the researchers who built them.

* Day 5: MLOps for Generative AI - Discover how to adapt MLOps practices for Generative AI and leverage Vertex AI's tools for foundation models and generative AI applications.





# Day 1

[Podcast day 1: Foundational LLMs & Text Generation](https://www.youtube.com/watch?v=mQDlCZZsOyo)

[White paper: Foundational LLMs & Text Generation](https://www.kaggle.com/whitepaper-foundational-llm-and-text-generation)

[Notes on Prompt Engineering](https://www.kaggle.com/whitepaper-prompt-engineering)

[ML notebook](https://www.kaggle.com/code/markishere/day-1-prompting)





