---
title: "Generative AI"
description: |
  An overview
author: "Chi Zhang"
date: "2024-10-29"
categories: [GenAI]
sidebar: false
code-block-bg: true
code-block-border-left: true
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
---


## Generative AI

AI systems that can produce high quality content, specifically text, images and audio

General purpose technology: like electricity, and AI

* web based: chat-gpt, bard, ...
* software based


History of LLM

* ELiza (1960s), pattern matching. Encourages introspection, creating the illusion of understanding to make people feel heard
* 2010s, GPT - generative pre-trained transformer by OpenAI
  * GPT2 (2018)
  * GPT3 (2020)
  * GPT4
* LlaMA by Meta



### Prompt engineering

Write, refine, optimize prompts; perfect the interaction between humans and AI; continuously monitor these prompts; maintain an up-to-date prompt library


Prompting guide

* give clear, specific prompt with context
* ask to include sources
* avoid leading the answer such that the answer is biased

Quality of the results

* accuracy
* unbiased
* sufficient information
* consistency if using the same prompt multiple times


Shot (examples): zero shot, one shot, few shot prompting (need to provide follow up information to make the answer more customized)

Chain of thought prompting: break down a large task into smaller sub-tasks




