---
title: "Data manipulation with data.table"
description: |
  `data.table` paradigm
author: "Chi Zhang"
date: "2024-04-20"
categories: [Data manip]
sidebar: false
code-block-bg: true
code-block-border-left: true
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
---


## data.table manipulation

```{r}
#| label: data
#| echo: true
#| eval: true
#| code-fold: true

# make some fake data
id <- c(
  rep(1, 3), 
  rep(2, 2), 
  rep(3, 6), 
  rep(4, 1)
)

ab_types <- c(
  'ampicillin', 'gentamicin', 'cefalotin', 'metronidazol'
)
ab <- sample(ab_types, size = length(id), replace = T)

dt <- data.table::data.table(
  id = id, ab = ab
)
dt
```


### By, .SD

Get number of records per person


```{r}
#| label: dot-n
#| echo: true
#| eval: true

dt[, .N, by = id]
```

Number of unique records

```{r}
#| label: sd
#| echo: true
#| eval: true

# if use lapply, the results will be a list in the column
dt[, .(n_uab = sapply(.SD, function(x){length(unique(x))})), 
   .SDcols = 'ab', 
   by = id]
```




