---
title: "Topic coverage: R developer"
description: |
  Topics that I should know as an R developer
author: "Chi Zhang"
date: "2023-10-05"
categories: [Interview]
sidebar: false
code-block-bg: false
code-block-border-left: true
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
---

::: {.callout-caution}

## This topic list does NOT include 

* shiny developer 
* statistical programmer (would require more on specific statistical packages)
* data scientist with a focus on engineering

:::

Resources: 

* [Advanced R](https://adv-r.hadley.nz/index.html)
* [R packages (2e)](https://r-pkgs.org)


Typical thought process:

* **What** is `x`
* **When** do you use `x`
* What are the **pros and cons** of `x`


::: {.callout-caution}

## Scattered knowledge dumpster

* vector: diff `na.rm = T` and `na.omit(x)`
* environment: function in global env. what does it mean (scope)
* error message: difference between `stop()` and `rlang::abort()`

data manipulation

* data table: why do I prefer to use it compared to tibble and df


:::



### R Programming

Foundations

- [ ] Data structures in R
- [ ] Environments

Functions and functional programming 

- [ ] `apply()` functions
- [ ] Evaluation
- [ ] Argument

OOP

- [ ] S3 generics


Debugging

- [ ] Something related to debugging


### Data manipulation

- [ ] Tidyverse suite 
- [ ] Text processing


### R package

- [ ] Development workflow
- [ ] R code and functions
- [ ] Data
- [ ] `DESCRIPTION`
- [ ] Dependencies and enviroment
- [ ] Testing
- [ ] Documentation: code
- [ ] Documentation: vignettes
- [ ] Doucmentation: website
- [ ] Maintenance










