---
title: "Software papers"
description: |
  Write and publish a software paper
author: "Chi Zhang"
date: "2023-10-27"
categories: [Publication]
sidebar: false
code-block-bg: true
code-block-border-left: true
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
---


Before writing a software paper, one needs to create a worthy software.

### Must

The following info are picked from [What I look for in 'Software Papers'](https://www.carlboettiger.info/2013/06/13/what-I-look-for-in-software-papers.html) by Carl Boettiger.

#### Pass CRAN checks

This is the minimal level of sufficiency.

* [CRAN policy](https://cran.r-project.org/web/packages/policies.html)

#### Automatic tests

* run by `R CMD check`
* examples in the documentation

#### Arguments: default and optional

For complex existing functions, allow possibility to provide more arguments.

```{r}
#| echo: true
#| eval: false

f <- myfunction(f, p, ...){ 
  #  stuff
  o <- optim(f, p, ...)
  #  stuff
}
```

For **default** arguments, think carefully whether they should be made default (e.g. numbers of iteration set to 100); or force users to specify it explicitly.


#### Development site on Github

So that users can raise issues.

#### Citation

Cite the packages I use as well.


### "Major revisions"

#### Functionalize the code

Shorter functions

#### Stable, clean, complete return objects

Return the argument (so that the additional arguments also show).

Use object classes and helper functions.

[Blogpost: We need more object oriented design in comparative methods](https://www.carlboettiger.info/2013/04/23/we-need-more-object-oriented-design-in-comparative-methods.html#comment-878249659)


## Select a journal

* R journal
* Journal of Open Source Software

### R journal 

To create a template, use `rjtools::create_article()`. This compiles both a pdf and html.

The article should have the following folders

* data 
* figures
* scripts
* motivation-letter


#### Troubleshooting

When the error is related to missing tex package: 

* in terminal, `tlmgr install texpkgname`


