---
title: "Clinical trial: reporting results"
description: |
  Notes related to clinical trial reporting
author: "Chi Zhang"
date: "2023-06-01"
categories: [Notes]
sidebar: false
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
---

### Resources 

* Coursera course [Design and interpretation of clinical trials](https://www.coursera.org/learn/clinical-trials/home/) by Johns Hopkins University




## CONSORT

Consolidated Standards of Reporting Trials

25 item checklist. Not a guideline of how to do the trial; but a guideline for writers on how to report clearly.

Title

* key design items
* treatment(s) evaluated 
* disease or population studied

Abstract

* design, method, results, conclusions

Introduction

* backgrounds, rationale, establish equipoise (balance), systematic review, objectives / hypothesis

Method 

* IRB review and approvals
* trial design, allocation ratio
* eligibility criteria
* setting and location of the trial
* intervention - detailed enough to allow replication
* outcomes - primary, secondary, how assessed and defined
* sample size - how determined, interim analyses
* important changes during trial
* randomization, allocation concealment, implementation
* masking - who, how
* statistical methods - primary and secondary; subgroup analyses

Convenient to use a flow-chart

Baseline characteristics by treatment group

p-values (common to not report in rct?)


### Evaluate literature

* Legitimacy, is it a fair comparison
* Trustworthy investigators? conflict of interest 
* Adequate protections against bias
  * randomization
  * masking
  * follow-up design and execution
* ITT analysis
  * have all events (outcomes) observed been counted in the treatment group assigned?
  * variations in denominators explained and consistent with good practice?
* **appropriate subgroup analysis interpretation**
  * ad hoc or post hoc status


