---
title: "Adaptive design: overview"
description: |
  Intro to adaptive design
author: "Chi Zhang"
date: "2023-08-26"
categories: [Design]
sidebar: false
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
---


Resources

* R package `rpact` and [tutorial](https://www.rpact.org/vignettes/getting-started/rpact_step-by-step_tutorial/)
* R package `gsDesign` and [tutorial](https://keaven.github.io/gsDesign/articles/gsSurvBasicExamples.html)




# Sequential design

Number of patient isn't set in advance. A good group sequential design can reduce the sample size needed, while keeping the desired statistical power and controlling the overall type I error.

GSD includes pre-determined number of stages (interim, final). Each stage specified by 

* sample size
* critical values
* stopping criterion to support or reject null hypothesis


TBC



# Basket and umbrella trials



# Interview questions

* Can you describe what an adaptive clinical trial design is and give an example of how it can be applied in oncology?
* What are the advantages and disadvantages of adaptive trial designs compared to traditional fixed designs?
* How would you adjust a trial protocol if interim analysis shows a promising treatment effect?










