---
title: "Notes from book: What if (Part x)"
description: |
  Instrumental variables
author: "Chi Zhang"
date: "2024-08-20"
categories: [Causal inference]
sidebar: false
code-block-bg: true
code-block-border-left: true
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
---


Instrumental variable estimation is one way that <u>does not</u> rely on the assumptions where all variables to adjust for confounding and selection bias to be identified and correctly measured. 

```{mermaid}
%%| label: dag1
flowchart LR
  Z[Z] --> A[A]
  A[A] --> Y{Y}
  U(U) --> A[A]
  U(U) --> Y{Y}
```

* Z is the random assignment indicator (1 treatment 0 placebo)
* A is the treatment (1 yes 0 no), not all adhere to original assignment
* Y is the outcome
* U is the unmeasured variables that affect both treatment adherence and outcome

### Conditions for instrument Z

1) Z is associated with A (treatment)
2) Z does not affect Y through its potential effect on A
3) Z and Y do not share causes

The three conditions are satisfied in a **double blind randomized controlled trial** as

1) those who are assigned to treatment (Z=1) are more likely to receive treatment (A=1), indicating association
2) expected in double blind design
3) expected by random assignment

There is a fourth condition of heterogeneity / monotonicity.

If an instrument is unmeasured, sometimes a proxy or **surrogate instrument** associated with the unmeasured instrument $U_z$ can be used.

### In observational studies

In observational studies we do not have the random assignment indicator Z. Some common categories of IV:

* genetic factors
* preference
* access to treatment


### Compare with other methods

The conditional exchangeability required by IP weighting, standardization is replaced by other assumptions. The choice of method depends on *whether it is easier* to identify and measure the confounders, or find an instrument Z and expect monotonicity and heterogeneity.

Violation of assumptions 1-4 may result in **large biases**; IP weighting and standardization are more robust compared to IV.

When there are **time varying treatment**, IV is not ideal as it is suited for point intervention.

### `ivreg` package

Check out [this post](https://cran.r-project.org/web/packages/ivreg/vignettes/ivreg.html) for an example. Only normal errors. 


