---
title: "Linear regression example: prestige"
description: |
  Linear regression
author: "Chi Zhang"
date: "2024-10-05"
categories: [Regression]
sidebar: false
code-block-bg: true
code-block-border-left: true
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
---

> This analysis is in preparation for interviews related to linear regression. Focus will be put on the procedure (and how to do it in R), as well as interpretation of the results.




```{r}
suppressMessages(library(car))
prestige <- carData::Prestige

m1 <- lm(prestige ~ education + income + women, 
         data = prestige)

summary(m1)
```

### T-test


### F-test

```{r}

m11 <- lm(prestige ~ education + income, data = prestige)
summary(m11)


m10 <- lm(prestige ~ education, data = prestige)
summary(m10)
```


```{r}
anova(m1, m11)
anova(m1, m10)
```


### Likelihood ratio test (less used)

```{r}
lmtest::lrtest(m1, m11) # not sig
lmtest::lrtest(m1, m10) # sig
```

### AIC, BIC

```{r}

AIC(m1, m11, m10) # m11 is the best
BIC(m1, m11, m10)
```

## Diagnostics

```{r}
par(mfrow = c(2, 2))
plot(m1)
```




