---
title: "Estimands, intercurrent events"
description: |
  Overview
author: "Chi Zhang"
date: "2024-03-28"
categories: [RCT]
sidebar: false
code-block-bg: true
code-block-border-left: true
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
---

Key question: how to present the data visually?

What are considered as important, what are not?


ITT (intention to treat): include the data after rescue medicine. Includes dropouts

PP (Per-protocol): exclude patients taking rescue medicine, only analyse the complete cases

Trial estimands: trial treatment effect depends on how events occur after treatment initiation.

Treatment effect for a given outcome.

Five core attributes

* population
* treatment conditions
* endpoint
* summary measure
* strategies to handle each type of intercurrent event

### Intercurrent event

Post-baseline events (post randomisation in RCT) that affects the interpretation of outcome.

Two categories: 

* treatment-modifying events, affects the receipt of assigned treatment. E.g. early discontinuation, use of rescue, wrong dose, wrong type (placebo for example).

* truncating events, e.g. death, amputation of limb when the limb is relevant for the research question.

Strategies (multiple can be used for different ICE in the same study)

* treatment policy strategy: treat as it is, ignore ICE
* composite strategy: modifies the endpoint value, defined by the investigator
* while-on-treatment (while alive): before intercurrent event data is used.
* hypothetical strategy
* principal stratum strategy: redefine the population








