---
title: "Genomics in Drug Discovery"
bibliography: biblio.bib
description: |
  Use of machine learning techniques
author: "Chi Zhang"
date: "2024-01-03"
categories: [Omics data]
sidebar: false
code-block-bg: true
code-block-border-left: true
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
---


Why do we need **precision medicine**? Late-stage failures cost the most, and small improvements in failure rates at early stage yield largest savings - use **better targets**.

As of 2016, 10-15% targets have genetic data; increased to 50%, expect 13-15% cost reduction.

Not all genes are targets, and not all targets are genes.

FTO (fat mass and obesity gene). Can search FTO in clinical trial gov website.

Overall nearly 60% are pursued by multiple companies, 26% by more than 5 companies: once a drug is made a target, redundancy is high. But before a target is proven, high diversity and novelty.


## Machine learning

Genomics data alone are insufficient for therapeutic development. How they interact with other types of data such as **compounds, proteins, EHR, images, texts etc** need to be investigated.

**Target discovery**: identify the molecure that can be targeted by a drug to produce a therapeutic effect, such as inhibition, to block the disease process. 

**Therapeutic discovery**: design potent therapeutic agents to modulate the target and block disease pathway. ML can be used to predict drug response in cell lines. Drug combination screening.

During **clinical studies**, ML can help characterize patient groups and identify eligible patients from gene expression data and EHRs. 

During **post-market studies**, mining EHR and other RWD to provid additional evidence, such as patients' drug response given different patient characteristics.


### Supervised learning

Regression and classification, e.g. 

* drug sensitivity prediction
* gene expression signitures that predict clinical trial success



### Unsupervised learning

Clustering, e.g. 

* feature reduction in single-cell data to identify cell types
* cell types and biomarkers from single-cell RNA data

Example: drug sensitivity predictive model. Identify biomarkers and build drug sensitivity predictive models using preclinical data, then apply to patients in early-stage clinical trials. Once validated, the model can be used for patient stratification and disease indicaation selection to support clinical development of a drug. 

(Example from [@Vamathevan2019])




# References

::: {#refs}
:::


https://www.iqvia.com/-/media/iqvia/pdfs/library/white-papers/machine-learning-applications-for-therapeutic-tasks.pdf

