---
title: "Interview: clinical trial statistician"
description: |
  Knowledge framework
author: "Chi Zhang"
date: "2024-10-02"
categories: [RCT]
sidebar: false
code-block-bg: true
code-block-border-left: true
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
---


> Book: Statistical design, monitoring and analysis of clinical trials




# Behavior

[List of behavior questions](interview_behavior.qmd)

# Statistics

### Study design

- [ ] [RCT design](rct_design_overview.qmd)
- [ ] [adaptive design](adaptive_design.qmd) 
- [ ] sample size [part 1](sample_size_1.qmd), [part 2](sample_size_2.qmd)
- [ ] power analysis
- [ ] Odds ratio, risk ratio ([Observational study design](observational_design.qmd))

::: {.callout-note collapse='true'}
## Relate to my own experience


:::

<details>
  <summary>Example questions</summary>
* why use OR instead of RR in case control studies

</details>




### Survival analysis

- [ ] [Kaplan-Meier, Cox proportional hazard](survival.qmd)
- [ ] [Competing risk](survival_competing_risk.qmd)
- [ ] Survival analysis in oncology

(datasets: `survival::pbc`)

::: {.callout-note collapse='true'}
## Relate to my own experience (hospital LOS)

use `ggsurvfit`

:::


### Hypothesis testing

- [ ] [general testing](hypothesis_tests.qmd)
- [ ] interim analysis

::: {.callout-note collapse='true'}
## Relate to my own experience


:::



### Longitudinal data

- [ ] repeated measurement analysis

(datasets: `mmrm::bcva_data`, `mmrm::fev_data`)

::: {.callout-note collapse='true'}
## Relate to my own experience (peanut, norkost)


:::


### Regression

([Regression](regression.qmd))

- [ ] assumptions and diagnostics <span style = 'color:red'>add poisson and nb</span>
- [ ] model selection
- [ ] interaction
- [ ] subgroup analysis
- [ ] confounding
- [ ] ANOVA, ANCOVA 


<details>
  <summary>Example questions</summary>
* what is confounding, how can you adjust for it

</details>



::: {.callout-note collapse='true'}
## Relate to my own experience: subgroup for COVITA


:::


### Missing data

- [ ] [missing data](imputation_1_overview.qmd) (major issue in oncology)
- [ ] drop-out handling, IIT vs per protocal

::: {.callout-note collapse='true'}
## Relate to my own experience


:::


### Meta analysis 





# Programming

* How would you implement survival analysis in R? Walk me through the process of creating Kaplan-Meier curves and performing Cox proportional hazards analysis.
* Can you explain how you would handle missing data using the mice package in R? Provide an example.
* What packages would you use for meta-analysis in R? Can you demonstrate how to perform a meta-analysis using the meta or metafor package?
* How would you simulate a clinical trial in R to calculate power? What tools or packages would you use for this purpose?
* Can you provide an example of how to perform bootstrapping to assess the robustness of a clinical trial result?



# Background

### Statistician's role

Workflow: design -> data collection, monitoring -> analysis

Design 

* define **primary and secondary endpoints**, need to be clearly **measurable** (e.g. progression free survival, overall survival, tumor response)
* randomization and blinding
* calculate **sample size**
* design study design (phase 1, 2, 3), sometimes adaptive design, Bayesian approach

Analysis

* survival (usually primary endpoint)
* censored data handling
* efficacy and safety: tumor shrinkage; QoL, side effects
* side effects frequencies
* subgroup analysis (need to pay attention to the risks of over-interpreting data)
* biomarker to predict treatment response

Reporting


### Regulatory

Regulatory and Compliance:

* Can you explain the ICH E9 guidelines, and why they are important in clinical trials?
* How would you prepare the statistical section of a regulatory submission for the FDA or EMA?
* What are the CONSORT guidelines, and how would you ensure compliance with them in reporting trial results?

Data Monitoring and Reporting:

* What is the role of a Data Safety Monitoring Board (DSMB), and how would you collaborate with them as a statistician?
* How do you ensure data integrity in the case of interim analyses or adaptive trial designs?


### Oncology

* In oncology, surrogate endpoints like progression-free survival (PFS) and overall response rate (ORR) are often used. How would you handle the analysis of these surrogate endpoints?
* Can you explain the RECIST criteria used for assessing tumor response in clinical trials?
* How do you design a basket trial or umbrella trial in oncology, and what statistical challenges do these designs present?



## Hospital vs Pharmaceuticals

#### Hospital

Topics of interest: long-term patient outcomes, QoL, comparative effectiveness of treatments, rare conditions that are less commercially viable. E.g. new surgical technique; compare different treatment regiments for patients with specific biomarkers

Design: more flexible and exploratory, novel designs; smaller, single centered trials; early-stage, proof-of-concept

#### Pharma

Topics of interest: strongly focused on meeting requirements of regulation, focus on predefined endpoints like efficacy and safety that align with drug approval processes. E.g. new cancer drug compared to placebo or existing treatment

Design: rigid design aligned with regulatory requirements; large, multicenter; RCT with precise inclusion/exclusion criteria





# Relevant experience


<details>
  <summary>Selected list of my statistical advising work</summary>
  
### Observational studies
  
| Study | Endpoint| Design  | Analysis | Comment |
|-------|-------|------|------|------|
| Hansen 2018 |  QoL on vocal surgical questionnaire, likert scale  | Case control, 3 groups: controls (no voice problem), test-retest group, surgical group   |  Cohen's kappa   |   Reliability of questionnaire   |
| Sarjomaa 2022 |    |    |     |  Tab 4    |
| Sarjomaa 2024 |    | Case control (with population)   |     |      |
| Kabashi 2019 |    | Cross-sectional, multi-site   |     |   Tab 2 and 3   |
| Fell 2024 |  CB prevalence  |    |     |      |
| Diab 2023 | ECG parameter. Pressure measures   |  n=20  | t-test or wilcoxon, correlation    |  Choice of method    |

### Clinical trials

| Study |Endpoint & Tx | Design  | Analysis | Comment |
|---------|---| -----|------|------|
| [Reier-Nilsen 2019](https://doi.org/10.1111/pai.13066) | QoL, Oral immunotherapy |  RCT, 2 year follow-up (T0, T1, T2). 2:1 block.   |     |      |
| Opdal 2023 | QT intervals. Methadone vs R-methadone   | n=9. SS based on one-sample t-test with effect size (QT in ms) 20/15   |     |   SS calculation   |
| Simonsen 2023 | QoL, stigma stress scale   | n=32, 1:1. Three endpoints (T0, T1, T2)   |     |  Revise study protocol, SS    |
| Callender 2023 |  Artery measures for blood flow  | n=26. Two legs, one tx one ct. Tx has 3 levels of stimulus. Within-subject design   |  Anova; or mixed model   |  Choice of method    |

Pay attention to how the sample size is calculated


</details>


For behavior questions check [here](interview_behavior.qmd)


::: {.callout-note collapse='true'}
## The kind of studies you've done

* by field: Covid; nutrition; 
* by design: 
* by endpoint: most are *QoL*

:::


::: {.callout-note collapse='true'}
## What do you like and dislike about the work

Like:  

* like to help clinicians understand their data
* like health data, sometimes you see very novel data types (e.g. measurements by the british doctor)
* interesting ways people carry out their studies

Dislike:

* communication (e.g. p-value interpretation)
* sometimes feels the frustration that the importance of data quality, processing is undervalued, and we are just p-value producers
* often need to re-work multiple rounds

:::

::: {.callout-note collapse='true'}
## Challenges you had in a study


:::






