---
title: "Interview: behavior"
description: |
  List of questions
author: "Chi Zhang"
date: "2024-10-06"
categories: [Design]
sidebar: false
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
---

> STAR: situation, task, action, result

# Highly relevant

### Collaboration & Communication	

Explain statistical concepts to non-experts; collaborate with cross-functional teams; resolve disagreements	

Tailoring technical language, teamwork, conflict resolution, and maintaining professional relationships

<details>
  <summary>Tell me about a time when you had to **explain complex statistical concepts** to a non-statistical audience (e.g., clinical staff or stakeholders). How did you ensure they understood?</summary>
 
 *Focus on how you tailor technical language to a non-technical audience.*
 
Case 1: teaching sensitivity, specificity to clinicians

* S: part of the statistics course, audience are not very familiar with math and probability
* T: this topic requires linking sens, spec with prevalence to show that rare disease screening with diagnostic tests have many false positives
* A: instead of looking at the formulae, use visual aids, draw some squares with different color to indicate the change of prevalence, and how a large proportion of positives indicated by a very sensitive test are actually false positives
* R: students appreciate the visual aids, positive feedback, and good test results
 
Case 2: teaching randomness and distribution with webR

* T: illustrate how fixed parameters for a distribution (such as normal) could take slightly different forms, difference of random seed
* A: make interactive code chunks in class, so students would try it
 
</details>


<details>
  <summary>Describe a situation where you collaborated with a **cross-functional team** (e.g., clinical researchers, data managers, regulatory staff) to complete a project. How did you ensure **effective communication and collaboration**?
</summary>
  *Focus on your teamwork and adaptability in a multidisciplinary setting.*
  
Case 1: work experience at FHI  
  
* S: covid times, surveillance, important to deliver reports in a timely manner
* T: maintain RT surv. system, with a range of people both inside the team (epi, project manager, technical people and web dev) and outside (infectious disease people, intl. network, media)
* A: we had different strength, I use my R skills to do the package maintenance, and quickly developed skills for shiny websites to support the team
* R: successful deliverables, improved the efficiency from 5 reports to thousands

Case 2: phd project

* S: 
* T: 
* A:
* R: 

</details>


<details>
  <summary>Have you ever faced a situation where the clinical team (or else) **disagreed** with your statistical analysis or interpretation of data? (can be any other disagreements such as work style..) How did you handle it?</summary>
  
  *Emphasize how you navigate differences of opinion, maintain professional relationships, and resolve conflicts.*

> statistical advising in general, sometimes have to choose different methods

Case 1: Phd AHUS paper

* S: paper collaborated with clinicians who provided data
* T: disagreement on how close to look at individual patients
* A: compromise from both side, do careful analysis in a next paper
* R: developed an R package to do that

Case 2: Norkost dietary report

* S: 
* T: need to carry out analysis with data provider
* A: 
* R: 



</details>

<details>
  <summary>Can you tell me about a time when you had to **meet tight deadlines** while ensuring the accuracy of your statistical work? How did you manage it?</summary>
  
*Highlight time management, prioritization, and quality control under pressure.*

Case 1: PhD dtw paper revision

* S: Review paper with major corrections
* T: lots of additional analysis to do
* A: implement, test fast, send to cluster to run at large scale. all while keeping an eye on the deadline, and leave sufficient time to revise and write
* R: managed to do it 

</details>



### Problem Solving & Adaptability

Identify and address data or analysis issues; manage incomplete data; adapt to protocol changes	

Analytical thinking, attention to detail, flexibility, ensuring study continuation

<details>
  <summary>Describe a time when you **identified a potential problem in the data** or the statistical analysis plan. How did you address it?</summary>
 
 *Focus on your problem-solving skills and attention to detail in identifying and rectifying errors.*
 
Case 1: PhD dtw paper revision

* S: 
* T: 
* A:
* R: 

</details>

<details>
  <summary><span style = 'color:red'>Important!</span>Have you ever encountered **incomplete or inconsistent data** during a clinical trial? How did you handle the situation, and what actions did you take to ensure the study's integrity?</summary>
  
  *Discuss your approach to data cleaning, imputation, or working with missing data.*

* S: 
* T: 
* A:
* R: 

</details>

<details>
  <summary>Tell me about a time when you had to **adapt quickly to changes** in a clinical trial protocol or **unexpected results** from an interim analysis (or else). How did you manage the change?</summary>
  
  *Highlight your adaptability, ability to pivot, and your role in ensuring the study’s continuation.*

Case 1: PhD dtw paper revision

* S: 
* T: 
* A:
* R: 

</details>




### Ethics & Compliance

Ensure regulatory compliance and handle sensitive data

Knowledge of FDA/EMA/ICH-GCP guidelines, ethical decision-making, data integrity & confidentiality


<details>
  <summary>Tell me about a time when you had to handle sensitive or confidential data. How did you ensure the **integrity and confidentiality** of the data?</summary>
 
 *Focus on data security, compliance with protocols (like HIPAA), and maintaining confidentiality.*
 
> Generally there is a system in place, such as TSD. So need to refuse the analysis when others breach it

Case: advising project

* S: clinician sent me very sensitive dataset via email
* T: 
* A: refused to work on it until it's properly denonymised
* R: 

</details>


### Leadership & Initiative	

Take initiative to improve processes; lead or mentor team members	

Process improvement, leadership, mentoring, aligning team with trial goals


<details>
  <summary>Describe a situation where you ((took the initiative** to **improve a process** or approach within your work. What was the outcome?</summary>
 
 *Highlight examples of process improvement, innovation, or contributions to more efficient study designs or analysis methods.*
 
Case: renovating statistical course with R and Quarto

* S: 
* T: 
* A:
* R: 

</details>


<details>
  <summary>Tell me about a time when you had to **lead or mentor** junior statisticians or team members during a study. How did you ensure they were aligned with the study’s goals and protocols?</summary>
  
  
  *Demonstrate your leadership, mentoring, and coaching skills.*

Case: noreden

* S: 
* T: 
* A: set out plan for the r programming part, set up schedule to sit together to work on problems, do quality check in the end; create documentation website for collaboration
* R: 


</details>




### Dealing with Challenges or Failures	

Manage unexpected challenges; learn from mistakes or trial failures	

Resilience, critical thinking, learning from setbacks, making informed decisions

<details>
  <summary>Can you tell me about a project that **did not go as expected** due to statistical issues or challenges? How did you **handle the situation** and what did you learn from it?</summary>
 
 *Showcase your resilience, learning from setbacks, and steps taken to mitigate future issues.*

Case: phd paper 3 which didn't go as planned

* S: 
* T: 
* A: use time in a better way, pivot to something else
* R: lesson learned: better planning would be ideal; find things to do;

</details>

<details>
  <summary><span style = 'color:red'>Important!</span>Describe a time when you had to **make a difficult decision** during a study, such as adjusting the analysis approach or advising the study to stop early based on statistical results. What was the outcome?</summary>
  
  *Focus on your critical thinking, ethical decision-making, and impact on trial success.*

Case: phd paper 3 which didn't go as planned

* S: 
* T: 
* A:
* R: 

</details>



### Attention to Detail & Accuracy	

Identify and correct errors; ensure precision in statistical work	

Meticulousness, responsibility, focus on ensuring trial success through accuracy


<details>
  <summary>Tell me about a situation where you **caught a mistake** in your own statistical work or in that of a colleague. How did you handle it and what was the result?</summary>
 
 *Highlight your meticulous attention to detail and responsibility in ensuring data accuracy.*
 
Case: COVITA study, table making

* S: 
* T: review the paper before submission
* A: tell the first author that it's crucial to change it
* R: 

Case: CB study, PCA analysis

* S: 
* T: reproduce the analysis made by someone else, unable to do so
* A: tell the first author that they need to revise 
* R: 
</details>

<details>
  <summary>Describe a time when your attention to detail significantly impacted the success or outcome of a study. What was at stake, and how did your actions make a difference?</summary>
  *Emphasize the importance of precision in statistical analysis and its effect on trial outcomes.*
  
Case: COVITA study, table making

* S: 
* T: 
* A:
* R: 

</details>





### Adaptation to Tools & Technologies	

Learn new software/tools for trial analysis	Quick learning, adaptability, proficiency with statistical tools (e.g., SAS, R)

<details>
  <summary>Can you tell me about a time when you had to learn and implement a **new statistical software or technology** for a clinical trial? How did you manage the learning curve?</summary>
 
 *Discuss your ability to quickly adapt to new tools, such as SAS, R, or other clinical trial software.*

> Use of AI 

Case: course website with R and quarto

* S: 
* T: 
* A:
* R: 

</details>



# Less relevant

### Work Under Regulatory Pressure	

Manage audits or regulatory scrutiny; maintain accuracy under pressure	

Composure, stress management, maintaining statistical precision under high stakes

<details>
  <summary>Describe a situation where you had to manage high levels of regulatory scrutiny or audit during a clinical trial. How did you handle the stress, and how did it affect your statistical work?</summary>
  *Talk about maintaining accuracy and composure under pressure, especially in high-stakes audits.*

* S: 
* T: 
* A:
* R: 
</details>



