---
title: "Observational study design"
description: |
  Cohort, case control and related metrics
author: "Chi Zhang"
date: "2024-10-06"
categories: [Design]
sidebar: false
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
---


Prospective studies: cohort. Population at risk and incidence are directly observed over time

Retrospective studies: CC.

In cohort studies and RCT, participants are selected based on **exposure** status; in CC studies, they are selected based on **outcome** status. 

## Relative risk (risk ratio) RR, odds ratio OR

### Case control studies

Odds ratio is usually used over risk ratio for the following reasons

* CC studies aim to compare the exposure history (risk factor) between cases and controls. As subjects are selected based on outcome, you can't compute **risk** (which measures the population)
* incidence or risk calculation: it is not directly measureable you do not have total number of people developing the disease. In CC typically matched as a ratio
* odds is computable
* in rare outcomes, OR approximates RR
* logistic regression estimates OR




# Interview questions

* Why use OR instead of RR










