---
title: "Survival"
format: 
  html:
    code-fold: false
    code-tools: false
editor: source
---

Links 

https://www.emilyzabor.com/tutorials/survival_analysis_in_r_tutorial.html

https://www.danieldsjoberg.com/ggsurvfit/

jmpost: combines survival analysis, mixed effect model https://genentech.github.io/jmpost/main/


## Basics 

Observed time $Y_i = min(T_i, C_i)$

- $T_i$ is event time
- $C_i$ is censoring time

Event indicator $\delta_i = 1$ if event observed ($T_i <= C_i$), 0 else.

Probability that a subject surves beyond given specific time: 

$$S(t) = Pr(T>t) = 1 - F(t)$$
where 

- $S(t)$ is the survival function
- $F(t) = Pr(T <= t)$ is the cumulative distribution function

Survival probability at a certain time t is a conditional probability of surviving beyond that time, given that an individual has survived just prior to that time. This can be estimated as the number of patients who are alive (without loss of follow-up), divided by the number of patients who were alive just prior to that time.


### Cox regression 

Semi-parametric model for survival outcome

$$h(t|X_i) = h_0(t) exp(\beta_1 X_{i1} + ... + \beta_p X_{ip})$$
where

- $h(t)$ is hazard, the instantaneous rate at which events occur 
- $h_0(t)$ is the underlying baseline hazard

Assumptions

- non-informative censoring
- proportional hazards

Hazard ratio HR: the ratio of hazards between two groups at any particular point in time. For example, HR = 0.59 (sex female) means 0.59 times as many females die as males *at any given time* - females have lower hazard of death than males.

### Landmark analysis

Covariates are measured at baseline - before follow-up time for the event begins

Examples of covariates that are not measured at baseline: transplant failure, compliance, adverse events


Landmark approach

- select a fixed time after baseline, this should be done based on clinical information
- subset population for those followed at least until landmark time
- calculate follow-up from landmark time, and apply log-rank tests or cox regression

It might be necessary to reset the time (for example by substracting the landmark time, say 90 days)


### Time-dependent covariate

This is more appropriate than landmark analysis when 

- value of a covariate changes over time
- there isn't an obvious landmark time
- use of landmark leads to too many exclusions




## Competing risks


Subdistribution hazards: modifies the traditional hazard function to account for probability of NOT experiencing the event of interest due to competing risks

Cumulative incidence function: used to estimate the probability of experiencing each type of event over time

Aalen-Johansen estimators $\hat{P}(T<=t, X_T = j), j = 1, 2$ add up to 1 minus Kaplan-Meier estimator $\hat{P}(T>t)$

Independence assumption: assuming competing events are mutually exclusive


### Nonparametric estimation

Cause-specific hazards $\alpha_{0j}(t), j = 1,2$ are key quantities of the competing risk model, its specification suffice to generate competing risk data (except censoring).

Nelson-Aalen estimator of the **cumulative** cause-specific hazards $A_{0j}(t) = \int_0^t \alpha_{0j}(u) du, j = 1,2$ 









## Multi-state modeling

Multi-state modeling is not only for time-to-event data. Competing risk is a special case for MS.

Models the transition between states: healthy to diseased, diseased to death, healthy to death etc

Transition probabilities

Transition hazards

State occupancy probabilities 

Use package `msm`, `mstate`, etc

### Use `msm`

Time of transition is unknown. The time in the dataset is *observed* state

Transition structure: defined by a matrix with $r, s$ entry. For example, for transitions allowed below

- 1 to 2
- 2 to 3
- 3 to 4

the transition matrix would be 

```{r}
#| eval: false
Q <- rbind(c(0, 1, 0, 0), 
           c(0, 0, 1, 0), 
           c(0, 0, 0, 1),
           c(0, 0, 0, 0))
```

Transitions should only be allowed in adjacent states in continuous time. For example, even if we observe 1 -> 3 without seeing the state 2, we know that patients have been through 1 -> 2 -> 3. The transition matrix should NOT be selected based on what we observe in the data!


Mean sojourn time (waiting time): $-1/q_{rr}$ is the expected time to stay in the same state (hence the $rr$). 












