---
title: "Google Cloud Machine Learning Engineer"
listing:
  - id: others
    fields: [title]
    contents: 
      - "cloud_overview.qmd"
    type: table
    sort: "title"
    filter-ui: false
    sort-ui: false
    categories: true
---

Resources

* [Google Cloud Skills Boost: Machine Learning Engineer Learning Path](https://www.cloudskillsboost.google/paths/17)
* [Google ML education](https://developers.google.com/machine-learning)
* [Professional MLE study guide](https://www.cloudskillsboost.google/paths/17/course_templates/1171)


### Objectives

1. **architecting low-code AI solutions**
  * develop ML models with BQML (C1M2, C2L1, C4 all, C5 all, C6M3, C16M3)
  * build AI solutions by using ML APIs or foundational models (C1M3, C2L7-9, C16L2, C17)
  * training models by using AutoML (C1 all, C3)
2. **collaborating within and across teams to manage data and models**
  * explore and process data (C1M2-4, C3, C5 all, C10)
  * model prototyping using Jupyter notebooks (C3)
  * tracking and running ML experiments (C16L1, C14)
3. **scaling prototypes into ML models**
  * building models (C8)
  * training models (C1M4, C12, C13, C8M3-6, C16L3)
  * choosing the right hardware (C8M3)
4. **serving and scaling models**
  * serving models (C6M1, C8M2, C16L3)
  * scaling online model serving (C6M1, )
5. **automating and orchestrating ML pipelines**
  * developing end-to-end ML pipelines (C1M4, C8, C9, C16L4)
  * automate model retraining (C16, C15)
6. **monitoring AI solutions**
  * identifying risks to ML solutions (C8M1,2,6, C18, C19, C20)
  * monitoring, testing, troubleshooting ML solutions (C16L1,L3,L5, C8M2,M6, C7M4)


### Curriculum

| ID |Chapter|  Topic | Resources |
|:--:|:-------:|:---------:|:---:|
| C1M1 | **Introduction to AI and Machine Learning on Google Cloud** |  AI Foundations on GC | [Notes](c1.qmd)   |
| C1M2 || AI development on GC |     |
| C1M3 ||  ML Workflow and Vertex AI |   | 
| C1M4 ||  GenAI on GC |    |
| C2L1 | **Prepare data for ML APIs on GC** |  Vertex AI  |  |
| C2L2 | |  Dataprep  |  |
| C2L3 | |  Dataflow  |  |
| C2L4 | |  Dataflow |  |
| C2L5 | |  Dataproc |  |
| C2L6 | |  Dataproc |  |
| C2L7 | |  Cloud NL API |  |
| C2L8 | |  Speech-to-text API |  |
| C2L9 | |   Video intelligence |  |
| C2L10 | |  Prepare data for ML API on GC |  |
| C3 | **Working with Notebooks in Vertex AI** |  Working with Notebooks in Vertex AI |  |
| C4L1 | **Create ML Models with BigQuery ML** | Getting started with BigQuery ML  |  |
| C4L2 | | Predict visitor purchases with classification with BQML |  |
| C4L3 | | Predict taxi fare with BQML   |  |
| C4L4 | | Bracktology with Google ML  |  |
| C4L5 | |Create ML models with BQML   |  |
| C5L1 | **Engineer Data for Predictive Modeling with BigQuery ML** | Create a data transformation pipeline with cloud dataprep  |  |
| C5L2 | | ETL processing  |  |
| C5L3 | | Predict visitor purchases|  |
| C5L4 | | Engineer data for predicitive modeling   |  |
| C6M1 | **Feature engineering** | Intro  |  |
| C6M2 | | Raw data to features   |  |
| C6M3 | | Feature engineering   |  |
| C6M4 | | Preprocessing and feature creation  |  |
| C6M5 | |  Feature crosses |  |
| C6M6 | |  Introduction to tensorflow transformation |  |
| C7L1 | **Tensorflow on GC** | TensorFlow ecosystem  |  |
| C7L2 | | Design and build an input data pipeline  |  |
| C7L3 | | Building Neural networks with TF and Keras   |  |
| C7L4 | |Training at scale with Vertex AI   |  |
| C8 | **Production ML systems** | *Less relevant*  |  |
| C9 | **MLOps: getting started** | *Less relevant*  |  |
| C10 | **MLOps with vertex AI: manage features** | *Less relevant*  |  |
| C11, C13 | **Intro to Generative AI**, MLOps |   |  |
| C12| **Intro to LLM** |   |  |
| C14| **MLOps with vertex AI: model evaluation**  | *Less relevant*   |  |
| C15| **ML Pipelines on GC** |  *Less relevant*  |  |
| C16L1 |**Build and Deploy Machine Learning Solutions on Vertex AI**  | Vertex AI  |  |
| C16L1 | | Identify damaged car parts with vertex AutoML vision  |  |
| C16L1 | | Deploy a BQML customer churn classifier  |  |
| C16L1 | | Vertex pipelines  |  |
| C16L5 | | Build and deploy ML solutions with vertex AI  |  |
| C17 | **Build GenAI apps on GC** |   |  |
| C18 | **Responsible AI: fairness and bias**|   |  |
| C19 | **Responsible AI: interpretability and transparency**|   |  |
| C20 | **Responsible AI: privacy and safety**|   |  |




### Other topics

::: {#others}
:::


