---
title: "Case study: CTN-51"
description: |
  Focusing on CTN 51 data
author: "Chi Zhang"
date: "2024-03-28"
categories: [RCT]
sidebar: false
code-block-bg: true
code-block-border-left: true
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false

---

## Study information

 [CTN 51](https://ctnlibrary.org/protocol/ctn0051/) ([Lee 2018](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(17)32812-X/abstract)): **Bup/Nx vs XR-NTX** naltrexone, effectiveness of pharmacotheerapeutic aids to recovery who completed detoxification and achieved short term abstinence. n=570
 
  * XR-NTX (n=283): induction hurdle, higher rate of 24-week relapse, fewer successfully initiated XR-NTX (204 of 283) than Bup/Nx (270 of 287)
  * for those inducted successfully, relapse rate is similar
  * relapse: 4 consecutive weeks of any non-study opioid use (UDS or report), or 7 consecutive days of self-reported use.
  


Reproduce some of the results, try to understand the events involved after initiation

Key numbers

* relapse is 4 consecutive weeks of non-study opioid use or 7 days of self-reported use
* ITT (n=570), 24 weeks relapse greater for NTX 
* pre-protocol (n=474), similar relapse
* relapse rate is between 57% to 65%


Things to understand

* initiation hurdle


## Datasets used 

```{r}
#| label: ctn51
#| echo: true
#| eval: true

library(public.ctn0094data)
library(public.ctn0094extra)
library(CTNote)
library(dplyr)
library(purrr)
library(tibble)
library(tidyr)
library(stringr)

out <- CTNote::outcomesCTN0094

# take c51 

everybody$project |> table() # this includes all eligible
out_c51 <- left_join(everybody, out) |> 
  filter(project == 51)
out_c51 |> head()
```



### Treatment and outcome related

Outcome includes pattern and class

Randomization


`treatment`: time is study day, amount is dose or 1 (injection)





